name: ies_warehouse
version: "1.0.0"
config-version: 2

profile: ies_warehouse

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ies_warehouse:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
