-- Core party and caseload entities. All identifiers are UUIDs generated by
-- the application, so a record's identity does not depend on insert order.

create table person (
    id                  uuid primary key,
    first_name          text        not null,
    last_name           text        not null,
    date_of_birth       date        not null,
    -- Tokenized stand-in for an SSN-like identifier. The real value never
    -- exists in this system; the token is what the warehouse ever sees.
    ssn_token           text        not null unique,
    sex                 text        not null check (sex in ('F', 'M', 'X')),
    is_us_citizen       boolean     not null default true,
    created_at          timestamptz not null default now()
);

-- HOUSEHOLD is IES's case record: one benefit case can span many
-- applications over its lifetime (an initial application, then renewals and
-- reported changes), which is why APPLICATION is 1:N off HOUSEHOLD rather
-- than the other way around. CASE_ASSIGNMENT (below) is keyed off
-- household_id for the same reason -- a worker owns the case, not a single
-- application.
create table household (
    id                  uuid primary key,
    -- The person whose circumstances anchor the case. Head-of-household is a
    -- real SNAP concept, not a UI convenience.
    head_person_id      uuid        not null references person (id),
    county              text        not null,
    -- Mailing/residential address for the case. Not effective-dated in
    -- Phase 1a (unlike income/expense/etc.) -- an address change mid-case is
    -- reported as a new row here in Phase 1b once change-of-circumstance
    -- workflows exist; Phase 1a treats it as current-value-only, same as
    -- county.
    address_line1       text        not null,
    address_line2       text,
    city                text        not null,
    state               text        not null,
    zip_code            text        not null check (zip_code similar to '[0-9]{5}(-[0-9]{4})?'),
    created_at          timestamptz not null default now()
);

create table household_member (
    id                  uuid primary key,
    household_id        uuid        not null references household (id),
    person_id           uuid        not null references person (id),
    relationship        text        not null check (relationship in
                            ('SELF', 'SPOUSE', 'CHILD', 'PARENT', 'OTHER_RELATIVE', 'UNRELATED')),
    purchases_and_prepares_food_together boolean not null default true,
    effective_from      date        not null,
    effective_to        date,
    created_at          timestamptz not null default now(),
    constraint household_member_effective_range check (effective_to is null or effective_to >= effective_from),
    constraint household_member_unique_span unique (household_id, person_id, effective_from)
);

create table worker (
    id                  uuid primary key,
    full_name           text        not null,
    email               text        not null unique,
    role                text        not null check (role in ('WORKER', 'SUPERVISOR', 'ADMIN')),
    created_at          timestamptz not null default now()
);

-- CASE_ASSIGNMENT is what makes caseload-scoped authorization possible at
-- all in Phase 1b. Created now because determinations reference the worker
-- who is accountable for the case.
create table case_assignment (
    id                  uuid primary key,
    household_id        uuid        not null references household (id),
    worker_id           uuid        not null references worker (id),
    effective_from      date        not null,
    effective_to        date,
    created_at          timestamptz not null default now(),
    constraint case_assignment_effective_range check (effective_to is null or effective_to >= effective_from)
);

create index household_member_household_idx on household_member (household_id, effective_from);
create index case_assignment_household_idx on case_assignment (household_id, effective_from);
